apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-integration
  namespace: kowsu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-integration
  template:
    metadata:
      labels:
        app: kubernetes-integration
    spec:
      containers:
        - name: kubernetes-integration
          image: kowsuram/kubernetes-integration:latest
          ports:
            - containerPort: 8080