apiVersion: v1
kind: Service
metadata:
  name: kubernetes-integration
  namespace: kowsu
spec:
  selector:
    app: kubernetes-integration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
